### ISSUE TITLE
Hello, I can't execute this command successfully according to your steps.

### ISSUE THREAD

**Issue by Rookie-flying** [robinhenry/gym-anm-exp#2] opened 2023-03-02 17:08 UTC
Obtaining file:///E:/PycharmProjects/gym-anm-exp
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "e:\anaconda\envs\torch\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "e:\anaconda\envs\torch\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "e:\anaconda\envs\torch\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "C:\Users\hx\AppData\Local\Temp\pip-build-env-y_5g_trz\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 41, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "C:\Users\hx\AppData\Local\Temp\pip-build-env-y_5g_trz\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 59, in __init__
          super().__init__(poetry, executable=executable)
        File "C:\Users\hx\AppData\Local\Temp\pip-build-env-y_5g_trz\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 83, in __init__
          self._module = Module(
        File "C:\Users\hx\AppData\Local\Temp\pip-build-env-y_5g_trz\overlay\Lib\site-packages\poetry\core\masonry\utils\module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package gym-anm-exp
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by robinhenry** [comment] 2023-03-02 22:20
I'm closing this issue, as this is a duplicate of https://github.com/robinhenry/gym-anm-exp/issues/3

**Closed as completed by robinhenry** 2023-03-02 22:20 UTC
